### ISSUE TITLE
Where is your implementation of Ironwood?

### ISSUE THREAD

**Issue by ghost** [majestrate/yggdrasil-cxx#1]
Why did you start developing yggdrasil-cxx not with the implementation of Ironwood - the routing and tree building core, but with network interaction? After all, all the complexity will be in working with Bloom filters, distributed CRDT data structures, eliminating loops, assessing priorities and cost of links, and so on. Sorry for my English.

**Comment by majestrate** [comment]
you can call this ironwood-cxx if you want but the primary end use is as a highly optimized version of yggdrasil using a tun interface so i started with the event loop to see how things would span out from that in practice. in practice yggdrasil-go looks like it's just a light wrapper around ironwood. This code barely exists at all, please don't mind the mess.
